name: im_localized
description: Flutter ICU compatible Localization library with support for JSONs, runtime parsing and injecting
version: 0.0.4
repository: https://github.com/i-m-cyber/im_localized

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.1
  intl: ^0.18.0
  logger: ^1.3.0
  path: ^1.8.3
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
