name: im_localized
description: Flutter ICU compatible Localization library with support for JSONs, runtime parsing and injecting
version: 0.0.16
repository: https://github.com/i-m-cyber/im_localized

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  args: ^2.4.2
  collection: any
  intl: ^0.19.0
  logger: ^2.0.2+1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
